DROP TABLE IF EXISTS CUSTOMERS;

CREATE TABLE CUSTOMERS (
    Customer_Id INT AUTO_INCREMENT  PRIMARY KEY,
    Customer_Name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS PINCODES;

CREATE TABLE PINCODES(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Pincode VARCHAR(200) NOT NULL
);

DROP TABLE IF EXISTS STATES;

CREATE TABLE STATES(
    Id INT AUTO_INCREMENT PRIMARY KEY,
    STATE VARCHAR(200) NOT NULL
);